services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile

  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
