'use client'

import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { ArrowRight, BadgeCheck, MapPin, Package, Send, ShieldCheck, Truck } from 'lucide-react'

import Header from '@/components/layout/Header'
import { Button } from '@/components/ui/Button'
import { createFreightRequest, estimateFreight, getFreightCommunes, getFreightRequests, markFreightDelivered, selectFreightOffer } from '@/lib/data/freight'
import { useAuthActionStore } from '@/store/authActionStore'
import { useAuthStore } from '@/store/authStore'
import type { FreightDraft, FreightRequest, FreightService } from '@/types/freight'

const initialDraft: FreightDraft = { service_type: 'fret_pro', departure_commune_id: '', destination_commune_id: '', cargo_type: '', volume_bucket: 'range_0_5_2', weight_bucket: 'lt_10', urgency: 'flexible', budget_max_xpf: '', description: '', contact_email: '', contact_phone: '', fragile: false, manutention: false }
const money = new Intl.NumberFormat('fr-FR', { maximumFractionDigits: 0 })

export default function FreightPageView() {
  const isAuthenticated = useAuthStore((state) => state.isAuthenticated)
  const user = useAuthStore((state) => state.user)
  const openAuthModal = useAuthActionStore((state) => state.openAuthModal)
  const [draft, setDraft] = useState(initialDraft)
  const [communes, setCommunes] = useState<Awaited<ReturnType<typeof getFreightCommunes>>>([])
  const [requests, setRequests] = useState<FreightRequest[]>([])
  const [selectedId, setSelectedId] = useState<number | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [notice, setNotice] = useState<string | null>(null)
  const [submitting, setSubmitting] = useState(false)

  const load = async () => { setLoading(true); setError(null); try { const [communeData, requestData] = await Promise.all([getFreightCommunes(), isAuthenticated ? getFreightRequests() : Promise.resolve([])]); setCommunes(communeData); setRequests(requestData); setSelectedId((current) => current || requestData[0]?.id || null); setDraft((current) => ({ ...current, departure_commune_id: current.departure_commune_id || String(communeData[0]?.id || ''), destination_commune_id: current.destination_commune_id || String(communeData[1]?.id || ''), contact_email: current.contact_email || user?.email || '', contact_phone: current.contact_phone || user?.telephone || '' })) } catch { setError('Le service de fret est momentanément indisponible.') } finally { setLoading(false) } }
  useEffect(() => { void load() }, [isAuthenticated])
  const estimate = useMemo(() => estimateFreight(draft, communes), [communes, draft])
  const active = requests.find((request) => request.id === selectedId) || requests[0] || null
  const field = 'min-h-12 w-full rounded-field border border-warm-border bg-cream px-4 text-base outline-none focus:border-ink focus:ring-2 focus:ring-ink/10'

  const submit = async (event: FormEvent) => { event.preventDefault(); setError(null); setNotice(null); if (!isAuthenticated) { openAuthModal({ type: 'publish_listing', redirectTo: '/fret' }); return } if (!draft.departure_commune_id || !draft.destination_commune_id || draft.departure_commune_id === draft.destination_commune_id) { setError('Choisissez deux communes différentes.'); return } setSubmitting(true); try { await createFreightRequest(draft); setNotice('Votre demande a été envoyée aux transporteurs disponibles.'); await load() } catch { setError('Impossible d’enregistrer votre demande pour le moment.') } finally { setSubmitting(false) } }
  const choose = async (requestId: number, offerId: number) => { setError(null); try { await selectFreightOffer(requestId, offerId); setNotice('L’offre a été sélectionnée.'); await load() } catch { setError('Impossible de sélectionner cette offre.') } }
  const delivered = async (requestId: number) => { setError(null); try { await markFreightDelivered(requestId); setNotice('La livraison est confirmée.'); await load() } catch { setError('Impossible de confirmer la livraison.') } }

  return <><Header /><main className="min-h-screen bg-cream text-ink"><section className="relative overflow-hidden bg-ink text-cream"><div className="absolute inset-0 bg-tressage text-cream/5" /><div className="relative mx-auto max-w-container px-4 py-12 sm:px-6 lg:px-12 lg:py-16"><p className="flex items-center gap-2 text-eyebrow uppercase text-accent"><Truck className="h-4 w-4" />Envoi et livraison</p><h1 className="mt-5 max-w-title font-display text-h1-form sm:text-h1">Décrivez votre envoi, les pros vous répondent.</h1><p className="mt-5 max-w-prose text-body-lg text-cream/75">Comparez librement les offres de transporteurs pour un colis, un déménagement ou du fret professionnel.</p></div></section>
    <section className="mx-auto grid max-w-container gap-8 px-4 py-10 sm:px-6 lg:grid-cols-[minmax(0,1fr)_23rem] lg:px-12"><form onSubmit={submit} className="rounded-block border border-warm-border bg-cream-surface p-5 shadow-card sm:p-8"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-eyebrow uppercase text-accent-text">Demande de transport</p><h2 className="mt-2 font-display text-h2">Votre besoin</h2></div>{estimate ? <div className="rounded-card bg-cream-sunken p-4 text-right"><p className="text-caption uppercase text-ink/55">Estimation</p><p className="mt-1 font-display text-price-sm">{money.format(estimate.estimated_min_xpf)} à {money.format(estimate.estimated_max_xpf)} F</p></div> : null}</div>
      <div className="mt-6 grid grid-cols-3 gap-2">{([['colis', 'Colis'], ['demenagement', 'Déménagement'], ['fret_pro', 'Fret pro']] as const).map(([value, label]) => <button key={value} type="button" onClick={() => setDraft((current) => ({ ...current, service_type: value }))} className={`min-h-12 rounded-control px-3 text-label-sm font-semibold ${draft.service_type === value ? 'bg-ink text-cream' : 'border border-warm-border bg-cream'}`}>{label}</button>)}</div>
      <div className="mt-6 grid gap-4 sm:grid-cols-2"><Field label="Commune de départ"><select value={draft.departure_commune_id} onChange={(event) => setDraft((current) => ({ ...current, departure_commune_id: event.target.value }))} className={field}><option value="">Choisir</option>{communes.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.provinceName}</option>)}</select></Field><Field label="Commune d’arrivée"><select value={draft.destination_commune_id} onChange={(event) => setDraft((current) => ({ ...current, destination_commune_id: event.target.value }))} className={field}><option value="">Choisir</option>{communes.map((item) => <option key={item.id} value={item.id}>{item.name} · {item.provinceName}</option>)}</select></Field><Field label="Marchandise"><input required value={draft.cargo_type} onChange={(event) => setDraft((current) => ({ ...current, cargo_type: event.target.value }))} className={field} placeholder="Nature et quantité" /></Field><Field label="Budget maximum"><input type="number" min={0} step={100} value={draft.budget_max_xpf} onChange={(event) => setDraft((current) => ({ ...current, budget_max_xpf: event.target.value }))} className={field} placeholder="Facultatif" /></Field><Field label="Volume"><select value={draft.volume_bucket} onChange={(event) => setDraft((current) => ({ ...current, volume_bucket: event.target.value }))} className={field}><option value="range_0_5_2">Petit volume</option><option value="range_5_15">Volume moyen</option><option value="gt_15">Grand volume</option></select></Field><Field label="Poids"><select value={draft.weight_bucket} onChange={(event) => setDraft((current) => ({ ...current, weight_bucket: event.target.value }))} className={field}><option value="lt_10">Moins de 10 kg</option><option value="range_10_50">10 à 50 kg</option><option value="range_50_200">50 à 200 kg</option><option value="gt_200">Plus de 200 kg</option></select></Field><Field label="Urgence"><select value={draft.urgency} onChange={(event) => setDraft((current) => ({ ...current, urgency: event.target.value }))} className={field}><option value="flexible">Flexible</option><option value="standard">Sous quelques jours</option><option value="urgent">Urgent</option></select></Field><Field label="Téléphone"><input value={draft.contact_phone} onChange={(event) => setDraft((current) => ({ ...current, contact_phone: event.target.value }))} className={field} /></Field></div>
      <Field label="Précisions"><textarea rows={5} value={draft.description} onChange={(event) => setDraft((current) => ({ ...current, description: event.target.value }))} className="w-full rounded-field border border-warm-border bg-cream p-4 text-base" /></Field><div className="mt-4 flex flex-wrap gap-3"><label className="flex min-h-11 items-center gap-2 rounded-pill border border-warm-border px-4 text-label-sm"><input type="checkbox" checked={draft.fragile} onChange={(event) => setDraft((current) => ({ ...current, fragile: event.target.checked }))} />Fragile</label><label className="flex min-h-11 items-center gap-2 rounded-pill border border-warm-border px-4 text-label-sm"><input type="checkbox" checked={draft.manutention} onChange={(event) => setDraft((current) => ({ ...current, manutention: event.target.checked }))} />Manutention souhaitée</label></div>{error ? <p className="mt-5 rounded-control border border-alert-error/30 p-3 text-body-sm text-alert-error" role="alert">{error}</p> : null}{notice ? <p className="mt-5 rounded-control bg-reef/15 p-3 text-body-sm text-reef-text" role="status">{notice}</p> : null}<Button type="submit" className="mt-6" loading={submitting} loadingLabel="Envoi…"><Send className="h-4 w-4" />Envoyer ma demande</Button></form>
      <aside className="space-y-5"><div className="rounded-block border border-warm-border bg-cream-surface p-6 shadow-card"><p className="text-eyebrow uppercase text-accent-text">Demande en cours</p>{loading ? <div className="mt-4 h-40 animate-pulse rounded-card bg-cream-sunken" /> : active ? <RequestPanel request={active} choose={choose} delivered={delivered} /> : <p className="mt-4 text-body-sm text-ink/65">Vos demandes et les offres reçues apparaîtront ici.</p>}</div><div className="rounded-block bg-ink p-6 text-cream"><ShieldCheck className="h-6 w-6 text-reef-onDeep" /><h3 className="mt-4 font-display text-h3">Vous gardez le choix</h3><p className="mt-3 text-body-sm text-cream/70">Les offres sont privées et le paiement reste hors plateforme.</p></div></aside>
    </section>{requests.length > 1 ? <section className="mx-auto max-w-container px-4 pb-12 sm:px-6 lg:px-12"><p className="text-eyebrow uppercase text-accent-text">Historique</p><h2 className="mt-2 font-display text-h2">Toutes vos demandes</h2><div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-3">{requests.map((request) => <button key={request.id} type="button" onClick={() => setSelectedId(request.id)} className="min-h-32 rounded-card border border-warm-border bg-cream-surface p-5 text-left shadow-card hover:border-ink"><p className="text-h5">{request.departure} → {request.destination}</p><p className="mt-2 text-body-sm text-ink/60">{request.cargoType}</p><p className="mt-3 text-meta font-semibold text-accent-text">{request.statusLabel} · {request.offersCount} offre(s)</p></button>)}</div></section> : null}</main></>
}

function RequestPanel({ request, choose, delivered }: { request: FreightRequest; choose: (requestId: number, offerId: number) => void; delivered: (requestId: number) => void }) { return <div className="mt-4"><div className="rounded-card bg-cream-sunken p-4"><p className="text-h5">{request.departure} → {request.destination}</p><p className="mt-2 text-body-sm text-ink/60">{request.cargoType}</p><span className="mt-3 inline-flex rounded-pill bg-info/15 px-3 py-1 text-caption font-semibold text-info-text">{request.statusLabel}</span></div>{request.offers.length ? <div className="mt-4 grid gap-3">{request.offers.map((offer) => { const selected = request.selectedOfferId === offer.id; return <article key={offer.id} className={`rounded-card border p-4 ${selected ? 'border-info bg-info/10' : 'border-warm-border'}`}><div className="flex justify-between gap-3"><div><p className="text-label">{offer.transporterName}</p><p className="mt-1 text-meta text-ink/60">★ {offer.transporterRating.toFixed(1)} {offer.transporterVerified ? '· vérifié' : ''}</p></div><strong className="font-display text-price-sm">{money.format(offer.amountXpf)} F</strong></div><p className="mt-3 text-meta text-ink/65">{offer.pickupDate} · {offer.pickupSlot}</p>{offer.message ? <p className="mt-2 text-body-sm text-ink/65">{offer.message}</p> : null}<button type="button" onClick={() => choose(request.id, offer.id)} className={`mt-3 min-h-11 rounded-control px-4 text-label-sm font-semibold ${selected ? 'bg-info text-ink' : 'bg-accent-strong text-cream'}`}>{selected ? 'Offre sélectionnée' : 'Choisir cette offre'} <ArrowRight className="ml-1 inline h-4 w-4" /></button></article> })}{request.selectedOfferId && request.status !== 'delivered' ? <Button variant="secondary" onClick={() => delivered(request.id)}>Confirmer la livraison</Button> : null}</div> : <p className="mt-4 rounded-card border border-dashed border-warm-border p-4 text-body-sm text-ink/60">Aucune offre reçue pour le moment.</p>}</div> }
function Field({ label, children }: { label: string; children: ReactNode }) { return <label className="mt-4 block text-label-sm font-semibold text-ink/70"><span className="mb-2 block">{label}</span>{children}</label> }
